### ISSUE TITLE
Use org.slf4j.Logger instead of default logging

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/tracey-protocol-eiffel#18]

**Comment by MadsNielsen** [comment]
@Andrey9kin if we're ever going to use this in Jenkins. I strongly suggest not doing this.

**Comment by Andrey9kin** [comment]
@MadsNielsen why?

**Comment by MadsNielsen** [comment]
@Andrey9kin i wouldn't do it because Jenkins uses java.util.logger to log errors, you can access these log from the log menu items in Jenkins. Im not to sure users would be able to browse errors like that if you switched to slf4j. Also what is the rationale behind switching? Not verbose enough output?

**Comment by Andrey9kin** [comment]
@MadsNielsen Stash is using slf4j and I thought to align. Let's leave as it is
